### ISSUE TITLE
covr breaks R mtext() when using math markup

### ISSUE THREAD

**Issue by ianthurlbeck** [r-lib/covr#419] opened 2020-02-12 10:10 UTC
A simple plot with a subscript in the mtext() is corrupted when running under covr/testthat.

Define a package function plot_bug() which just does:

 plot(1:10)
 mtext(expression(paste("Log"[{10}]," Annual ratio",sep="")))

save it to the testdata/plots folder.

The the unit testthat test re-generates the plot and compares the 2 using isSimilar() from the visualTest package:

        png(tmpfile)
        plot_bug()
        dev.off()
        expect_true(isSimilar(tmpfile, getFingerprint("../testdata/plots/plot_bug.png")))

This fails. Somehow the math expression is corrupted with some internal covr data, see plots below:

![plot_correct](https://user-images.githubusercontent.com/48912009/74324994-cafd3a80-4d7f-11ea-8a60-98199bdfe265.jpg)

and the failing one:

![plot_broken](https://user-images.githubusercontent.com/48912009/74325043-da7c8380-4d7f-11ea-9140-21cad23c9dbf.jpg)

**Comment by jimhester** [comment] 2020-03-06 16:45
The problem is the braces, in `[{10}]`, do you need them in this case, I seem to get the same output without them.

**Comment by jimhester** [comment] 2020-04-03 13:31
While I can reproduce this bug, it is uncommon enough and fixing it would be challenging enough that I am going to close this issue. If others run into this same situation I will re-open it.

**Closed by jimhester** 2020-04-03 13:31 UTC
Labels: bug
