### ISSUE TITLE
covr and devtools::test disagree on some function objects equivalence

### ISSUE THREAD

**Issue by GeoBosh** [r-lib/covr#436] opened 2020-06-04 15:33 UTC
I know that equality of objects containing environments is a matter of definition but report this since under `covr` I obtained different results for some tests compared to just running `devtools::test() or `R CMD check`. 

It is difficult for me to devise a reprex. The following is an excerpt from one of the last lines, now commented, of [test-exampleModels.R](https://github.com/GeoBosh/mixAR/blob/master/tests/testthat/test-exampleModels.R). In essence the problem arises when comparing two function components of the compared objects. The following comparison succeeds in `devtools::test()` (also under `R CMD check`) 
```
expect_equal(moT_B, exampleModels$WL_Bt_1)
```
but `covr::report()` (also on TravisCI) throws error and reports that
```
## Attributes: < Component "dist": Component "generator":
##        target, current do not match when deparsed
```
Those objects look the same:
```
moT_B@dist$generator
## function(par = numeric(0)){
##                 dist <- ed_skeleton(par, fixed = fixed, n = length(type), tr = tr)
##                 for(i in seq_along(type)){
##                     dist[[i]] <- dist[[i]](ed_src[[ type[i] ]])
##                 }
##                 dist
##             }
## <environment: 0x55a7fea7e9c0>

exampleModels$WL_Bt_1@dist$generator
## function(par = numeric(0)){
##                 dist <- ed_skeleton(par, fixed = fixed, n = length(type), tr = tr)
##                 for(i in seq_along(type)){
##                     dist[[i]] <- dist[[i]](ed_src[[ type[i] ]])
##                 }
##                 dist
##             }
## <environment: 0x55a7ff72b258>
```
apart from the environments of course. Their environments are `expect_equal`:
```
expect_equal(environment(exampleModels$WL_Bt_1@dist$generator),
                       environment(moT_B@dist$generator))
```
The enclosing environments in both cases are the package environments:
```
parent.env(environment(moT_B@dist$generator))
## <environment: namespace:mixAR>
parent.env(environment(exampleModels$WL_Bt_1@dist$generator))
## <environment: namespace:mixAR>
```
Could it be that under `covr` the comparison doesn't stop when hitting the namespace of the package?

**Comment by jimhester** [comment] 2020-06-04 15:49
This is a duplicate of https://github.com/r-lib/covr/issues/423. Basically the way covr works is it modifies your packages' functions to add tracing calls, so comparing function equality with a function that does not have the tracing calls will always fail. I would suggest you refrain from writing tests like this, or skip them when running under covr.

**Closed by jimhester** 2020-06-04 15:49 UTC
